Welcome to Data Driven Astronomy online course organised by Positron Foundation

# **Python Refresher and Introduction to Astronomical data**

In this notebook we'll be checking your basic python basics through few simple problems.

Packages used:

Numpy<br>
Pandas <br>
Matplotlib



# **Initialization**

Run all the cells below

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Do not change 
!git clone https://github.com/Jack3690/DDA  

Cloning into 'DDA'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 65 (delta 19), reused 47 (delta 8), pack-reused 0
Unpacking objects: 100% (65/65), done.


In [4]:
cd DDA/Week_1/data 

/content/DDA/Week_1/data


# **Numpy**

Documentation : https://numpy.org/doc/stable/reference/index.html 

## **Problem I**
Write a function which performs operation shown below <br>
 $\hspace{5pt}$  Input $\hspace{25pt}$ Output \\
$\begin{bmatrix}
1 & 2 \\
4 & 3 
\end{bmatrix}
\rightarrow
\begin{bmatrix}
4 & 1 \\
3 & 2 
\end{bmatrix}$

In [2]:
A=np.array([[1,2],
             [4,3]])
# Write a function which takes above array as input and performs a clock-wise rotation of elements
# Hint : Rotational matrices
def rot(A):
  r=np.array([[0,1],
             [1,0]])
  return (r@A).T      # Transpose of r dot A. Here @ is matrix multiplication operator
print("Input\n",A,"\n\nOutput \n",rot(A))

Input
 [[1 2]
 [4 3]] 

Output 
 [[4 1]
 [3 2]]


## **Problem II**

Repeat problem I for an nxn matrix. Also let user decide whether to rotate clockwise or anti clockwise

In [3]:
# Matrix shape input from
n=int(input("Enter Matrix shape : "))
print(f"Matix shape : {n} x {n}")

ch=(input("Clock wise or anti clockwise (A/C) : "))

# nxn matrix Generator
A=np.arange(0,1000,1000/(n**2)).reshape(n,n)
print(f"\n{n} x {n} Matrix :\n\n",A)

# Write a function which takes array and direction of rotion as input and returns array with elements rotated accordingly
# Hint : Find a general formula for making nxn rotational matrix 

def rotn(A,ch):
  n=A.shape[0]
  r=np.zeros((n,n))
  for i in range(n):
    r[i,n-i-1]=1
  print("\nRotational Matrix :\n\n",r)

  if ch=='C' or ch=='c':
    return (r@A).T
  elif ch=='A' or ch=='a':
    return (A@r).T
  else :
    return "Choose A or C "

# Just for cosmetic purpose
dir={ 'A': "Anti-Clockwise",
      'C' : "Clockwise"}
print(f"\nMatrix after rotating along {dir[ch.upper()]} direction :\n\n",rotn(A,ch))

Enter Matrix shape : 2
Matix shape : 2 x 2
Clock wise or anti clockwise (A/C) : a

2 x 2 Matrix :

 [[  0. 250.]
 [500. 750.]]

Rotational Matrix :

 [[0. 1.]
 [1. 0.]]

Matrix after rotating along Anti-Clockwise direction :

 [[250. 750.]
 [  0. 500.]]


## **Bonus Problem : 3x3 Rubik's Cube**
Define a function which can rotate any chosen slice of a 3 x 3 x 3 matrix

 ![alt text](https://media.geeksforgeeks.org/wp-content/uploads/3D-array.jpg)

In [ ]:
"""
Slices 
Top Bottom
Left Right
Front Back

"""
slice_=input("Enter side : ")



# **Pandas**
Documentation :https://pandas.pydata.org/pandas-docs/stable/reference/index.html

About Data : https://arxiv.org/abs/1406.4179

In [5]:
df=pd.read_csv('meert.csv')
df

,ra,dec,z,veldisp,veldispErr,eclass,p_el_debiased,p_cs_debiased,spiral,elliptical,uncertain
0,236.247,-0.475264,0.030284,-9999.000,-9999.0000,0.159350,0.165,0.739,0,0,1
1,236.287,-0.518003,0.077923,-9999.000,-9999.0000,0.054718,0.029,0.937,1,0,0
2,236.342,-0.467023,0.160228,-9999.000,-9999.0000,-0.120854,0.211,0.763,0,0,1
3,236.350,-0.598237,0.071558,-9999.000,-9999.0000,-0.043624,0.171,0.787,1,0,0
4,236.369,-0.574450,0.071975,-9999.000,-9999.0000,-0.068106,0.019,0.981,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
670717,217.363,1.049700,0.086556,131.273,10.7453,-0.163945,1.000,0.000,0,1,0
670718,226.463,1.074650,0.087805,-9999.000,-9999.0000,0.027229,-888.000,-888.000,-888,-888,-888
670719,226.547,1.114430,0.104590,-9999.000,-9999.0000,-0.131829,-888.000,-888.000,-888,-888,-888
670720,226.596,1.148130,0.126815,-9999.000,-9999.0000,0.048498,-888.000,-888.000,-888,-888,-888


## **Problem I (a)**
Find the minimum, maxium and mean redshift(z) of data

In [6]:
df['z'].describe()

count    670722.000000
mean          0.107776
std           0.053485
min           0.005007
25%           0.068795
50%           0.101573
75%           0.140906
max           0.843643
Name: z, dtype: float64

## **Problem I (b)**

# **Matplotlib**

Documentation : https://matplotlib.org/3.1.1/api/index.html