Welcome to Data Driven Astronomy online course organised by Positron Foundation

# **Python Basics Refresher**

In this notebook we'll be checking your basic python basics through few simple problems.

Packages used:

Numpy : https://numpy.org/doc/stable/reference/index.html
Pandas : https://pandas.pydata.org/pandas-docs/stable/reference/index.html
Matplotlib https://matplotlib.org/3.1.1/api/index.html


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Numpy**

## **Problem I**
Write a function which performs operation shown below <br>
 $\hspace{5pt}$  Input $\hspace{25pt}$ Output \\
$\begin{bmatrix}
1 & 2 \\
4 & 3 
\end{bmatrix}
\rightarrow
\begin{bmatrix}
4 & 1 \\
3 & 2 
\end{bmatrix}$

In [57]:
A=np.array([[1,2],
             [4,3]])
# Write a function which takes above array as input and performs a clock-wise rotation of elements
# Hint : Rotational matrices
def rot(A):
  r=np.array([[0,1],
             [1,0]])
  return (r@A).T      # Transpose of r dot A. Here @ is matrix multiplication operator
print("Input\n",A,"\n\nOutput \n",rot(A))

Input
 [[1 2]
 [4 3]] 

Output 
 [[4 1]
 [3 2]]


# **Problem II**

Repeat problem I for an nxn matrix. Also let user decide whether to rotate clockwise or anti clockwise

In [77]:
# Matrix shape input from
n=int(input("Enter Matrix shape : "))
print(f"Matix shape : {n} x {n}")

ch=(input("Clock wise or anti clockwise (A/C) : "))

# nxn matrix Generator
A=np.arange(0,1000,1000/(n**2)).reshape(n,n)
print(f"\n{n} x {n} Matrix :\n\n",A)

# Write a function which takes array and direction of rotion as input and returns array with elements rotated accordingly
# Hint : Find a general formula for making nxn rotational matrix 

def rotn(A,ch):
  n=A.shape[0]
  r=np.zeros((n,n))
  for i in range(n):
    r[i,n-i-1]=1
  print("\nRotational Matrix :\n\n",r)

  if ch=='C' or ch=='c':
    return (r@A).T
  elif ch=='A' or ch=='a':
    return (A@r).T
  else :
    return "Choose A or C "

# Just for cosmetic purpose
dir={ 'A': "Anti-Clockwise",
      'C' : "Clockwise"}
print(f"\nMatrix after rotating along {dir[ch.upper()]} direction :\n\n",rotn(A,ch))

Enter Matrix shape : 2
Matix shape : 2 x 2
Clock wise or anti clockwise (A/C) : a

2 x 2 Matrix :

 [[  0. 250.]
 [500. 750.]]

Rotational Matrix :

 [[0. 1.]
 [1. 0.]]

Matrix after rotating along Anti-Clockwise direction :

 [[250. 750.]
 [  0. 500.]]


# **Bonus**
Define a function which can rotate any chosen slice of a 3 x 3 x 3 matrix

 ![alt text](https://media.geeksforgeeks.org/wp-content/uploads/3D-array.jpg)

In [ ]:
"""
Slices 
Top Bottom
Left Right
Front Back

"""
slice_=input("Enter side : ")



Data types in Python

In [ ]:
i = 1      #Integer
j= 3.1416  #Floating Point 
k = 1 + 2j #Complex Number 
l = True   #Boolean Variable
print(i,type(i))
print(j,type(j))
print(k,type(k))
print(l,type(l))

Mathematical operations using Python


In [ ]:
a = 3 # Try different data types
b = 2 
print("Value of a =",a,"and b =",b)
print("a+b  = " ,(a+b))
print("a-b  = " ,(a-b))
print("a*b  = " ,(a*b))
print("a/b  = ",(a/b))
print("a//b = ",(a//b))
print("a%b  = ",(a%b))
print("a**b = ", (a**b))

**Tuples ()**

Sequence of values (which can be of mixed types) which are immutable(can't change it), written within parantheses

In [ ]:
tuple1=('p','o','s','i','t','r','o','n',3,1,4,1,5,9,2,6,5,3)

To access the elements, use the indices (starting from zero)

In [ ]:
print("0th element of tuple1 is",tuple1[0]) # Try changing index
print("Size of tuple1 is",len(tuple1)) # len() gives size of variable

A very useful trick is index slicing, where you can access a subset of the tuple. This works as follows

In [ ]:
tuple1[3:9] # [inclusive:exclusive]

The full syntax for index slicing is [inclusive_start:exclusive_end:step_size], so you can get something like

In [ ]:
tuple1[1:9:2]

In [ ]:
tuple1[3::3] # Starts slicing from index 3 with step size 3

Count backwards using negative indices

In [ ]:
tuple1[-3]

Lists []
Lists are mutable. Otherwise, they have similar properties to a tuple

In [ ]:
nested_list=[[1,2,3],['x','y','z'],['Data','Driven','Astronomy']] # You can also have nested tuples!

Nested lists are essentially lists within lists. Nested lists will feature a good deal in our tutorials later, so this is important.

Nested lists (or tuples) have more than one index, which can be used as follows:

In [ ]:
nested_list[:][2] # Play around with this!

With a list, you can change entries, append new ones, or delete some

In [ ]:
my_list=['Data',1,6,9,'Astronomy']
my_list[1]=3.26
print(my_list)

In [ ]:
my_list.append(['RGB','Analysis']) # This will be important later!
print(my_list)

In [ ]:
del my_list[1:4]
print(my_list)

In [ ]:
import numpy as np  # Numpy is a package with

In [ ]:
i=9  # Try giving different values to see changes in output
if i>3 :
  print("First level ",i)
elif i==2:                    # == checks for equality
  print("Second Level", i)
else:
  print("Third Level", i)



You can have more complex conditions

In [ ]:
i=6   # Try giving different values to see changes in output
if 2<i<5:
  print(i,"is between 2 and 5")
elif 5<i<8:
  print(i,"is between 5 and 8")
elif 8<i<20:
  print(i,"is between 8 and 20")

Logical 'and' & 'or

In [ ]:
i=3
j=6
if i>2 and j>6:  # logical "and", true when both conditions are satisfied 
  print("First condtion true")
elif i>2 or j>6: # logical "or", true when atleast one of conditions is satisfied 
  print("Second condition true")

Second condition true


Loops
There are two types of loops: for and while.

The usage is very straightforward, but there are perks and perils to both of these that we will explore in detail later.

In [ ]:
for i in [1,2,3,4]:
    print(i)


You can do this using range() function as well

In [ ]:
for i in range(1,4): # mathematicallu [1,4) end value not included
  print(i)

Range function syntax is range(start,stop,step_size)

In [ ]:
for i in range(1,10,2):
  print(i)

In [ ]:
i=0
while(i<5): 
  print(i)
  i=i+1    # updates the value of i

Now say you have to span across elements of a list of unknown size. You have two options

In [ ]:
X=[1,2,3,4,5,6,7,8]

for i in range(len(X)):
  print(X[i])

Or

In [ ]:
X=[1,2,3,4,5,6,7,8]

for i in X:
  print(i)       # here variable i takes values and spans the list

#**User Defined Function**#
We have seen functions like range(), len(). These are already existing functions. You too can define your own functions with following syntax

def function_name(arguments):<br> 
>     operation
    .
    .
    .
    return _something_

Following is a function to find area of a circle

In [ ]:
#Funtion to calculate area
def area_of_circle(r):
  area=3.1416*r**2        # r**2 = r raised to the power 2
  return area

# Input() function takes input froom user. Here it's been converted to integer and assigned to 'a'
a=int(input("Enter radius of circle : "))

print("Area of circle with radius",a,"is",area_of_circle(a))


# **Numpy**
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays<br>
https://numpy.org/

In [ ]:
import numpy as np #This state imports the functions of numpy and makes them accessible through variable np
print(np.sin(0))


In [ ]:
arr=np.zeros((3,3),float) #Creates a 3x3 matrix with all elements set to zero and data type float
print(arr)
print(type(arr)) # Observe that data type has changed

In [ ]:
brr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(brr)

In [ ]:
print(brr[:,0]) #sliced the array such that only 1 coloumn is printed

In [ ]:
print(brr[:,0:1]) # Notice the difference even though the elements are same

#**Strings**
We have seen strings before. They are, in a way, similar to tuples, where you can access each individual element (in this case the characters of the strings) using the indices; you can also use index slicing.

In [ ]:
char="Positron"
print(char[0])
print(len(char))


In [ ]:
ch1="Positron"
ch2="Foundation"

ch3=ch1 + " " + ch2 #Concatenation

print(ch3)

# **Plots**
Now lets move onto plotting. We'll use matplotlib(https://matplotlib.org/) for this

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0,2*np.pi,1000) # this function creates an numpy array and stores value between 0 and 2pi
y=np.sin(x)

print(len(x),type(x))

plt.plot(x,y)
plt.grid('on')
plt.xlabel("x")
plt.ylabel("y")
plt.show()


#**Timing**
You can use the time library to find out how much time your script is taking to run

In [ ]:
import time
count=0
start=time.perf_counter()
for i in range(100):
  count=count+1
end=time.perf_counter()-start
print("Time take :",end)

# **Assignment**

Complete the following tasks to proceed



1.   Write a code to print the following patterns:<br>
  a)<br>
  @@@@<br>
  @@@<br>
  @@<br>
  @<br>
  b)<br>
  11111<br>
  10001<br>
  10001<br>
  10001<br>
  11111

2.   Create a function which takes string like "Red" as input and gives following output:<br>
  Ex. 1<br>
  I want a Red car<br>
  Ex. 2<br>
  I want a Blue car<br>
  **Hint**: Use concatenation
3. Write a function which return distance between two points in cartesian space<br>

In [ ]:
#Complete the code
def calculate_distance(X,Y):

  dist=                    # Write formula for calculating distance. Remember X and Y are lists
  return dist**(0.5)

X=[0,0,0]
Y=[1,1,1]
distance=calculate_distance(X,Y)
print(distance)

4. Write a function which takes a list as input and return the maximum value from the list of number

In [ ]:
def find_max(X):
  #Complete the function to find the maximum value
  #Hint: First assume a max value 0



  
    
Y=[3.1,4.1,5.9,2.6,5.3,5.8,9.7,9.3,2]
print(find_max(Y))
